# Generated by Django 5.1.4 on 2025-01-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escort',
            name='whatsapp',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='girl',
            name='whatsapp',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='guy',
            name='whatsapp',
            field=models.CharField(max_length=225),
        ),
    ]
