# Generated by Django 5.1.4 on 2025-01-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gender', '0002_alter_escort_whatsapp_alter_girl_whatsapp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escort',
            name='area',
            field=models.CharField(default='Downtown', max_length=255),
        ),
        migrations.AddField(
            model_name='escort',
            name='dislikes',
            field=models.TextField(blank=True, default='None'),
        ),
        migrations.AddField(
            model_name='escort',
            name='dress_size',
            field=models.CharField(default='M', max_length=10),
        ),
        migrations.AddField(
            model_name='escort',
            name='height',
            field=models.CharField(default='Average', max_length=10),
        ),
        migrations.AddField(
            model_name='escort',
            name='hours_available',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='escort',
            name='languages_spoken',
            field=models.TextField(default='English'),
        ),
        migrations.AddField(
            model_name='escort',
            name='likings',
            field=models.TextField(blank=True, default='None'),
        ),
        migrations.AddField(
            model_name='escort',
            name='skin',
            field=models.CharField(default='Fair', max_length=20),
        ),
        migrations.AlterField(
            model_name='profilepicture',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics/'),
        ),
    ]
