# Generated by Django 5.1.4 on 2025-01-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gender', '0003_escort_area_escort_dislikes_escort_dress_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AvailableHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_range', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='escort',
            name='area',
        ),
        migrations.RemoveField(
            model_name='escort',
            name='hours_available',
        ),
        migrations.RemoveField(
            model_name='escort',
            name='languages_spoken',
        ),
        migrations.AddField(
            model_name='escort',
            name='areas',
            field=models.ManyToManyField(blank=True, to='gender.area'),
        ),
        migrations.AddField(
            model_name='escort',
            name='hours_available',
            field=models.ManyToManyField(blank=True, to='gender.availablehour'),
        ),
        migrations.AddField(
            model_name='escort',
            name='languages_spoken',
            field=models.ManyToManyField(blank=True, to='gender.language'),
        ),
    ]
