# Generated by Django 5.1.4 on 2025-01-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gender', '0004_area_availablehour_language_remove_escort_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escort',
            name='vip',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
