# Generated by Django 5.1.4 on 2025-01-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gender', '0005_escort_vip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escort',
            name='vip',
            field=models.BooleanField(default=False),
        ),
    ]
