# Generated by Django 5.1.4 on 2025-01-09 08:56

import gender.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gender', '0006_alter_escort_vip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='escort',
            old_name='vip',
            new_name='premium',
        ),
        migrations.AddField(
            model_name='escort',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='escort',
            name='new_until',
            field=models.DateTimeField(default=gender.models.get_default_new_until),
        ),
        migrations.AddField(
            model_name='escort',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
