# Generated by Django 5.1.4 on 2025-01-11 17:04

import django.utils.timezone
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gender', '0008_escort_calls'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', tinymce.models.HTMLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.RemoveField(
            model_name='guy',
            name='habits',
        ),
        migrations.RemoveField(
            model_name='girl',
            name='habits',
        ),
        migrations.RemoveField(
            model_name='escort',
            name='habits',
        ),
        migrations.RemoveField(
            model_name='escort',
            name='languages_spoken',
        ),
        migrations.RemoveField(
            model_name='escort',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='escort',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='escort',
            name='likings',
        ),
        migrations.RemoveField(
            model_name='girl',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='guy',
            name='gender',
        ),
        migrations.AlterField(
            model_name='escort',
            name='calls',
            field=models.CharField(default='outcalls & incalls', max_length=20),
        ),
        migrations.AlterField(
            model_name='escort',
            name='city',
            field=models.CharField(default='Kampala', max_length=255),
        ),
        migrations.AlterField(
            model_name='escort',
            name='dress_size',
            field=models.CharField(default='Straight', max_length=10),
        ),
        migrations.AlterField(
            model_name='girl',
            name='city',
            field=models.CharField(default='Kampala', max_length=255),
        ),
        migrations.AlterField(
            model_name='guy',
            name='city',
            field=models.CharField(default='Kampala', max_length=255),
        ),
        migrations.DeleteModel(
            name='Habit',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
