# Generated by Django 5.1.4 on 2025-01-15 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gender', '0010_blogpost_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilepicture',
            name='girl',
        ),
        migrations.RemoveField(
            model_name='guy',
            name='services',
        ),
        migrations.RemoveField(
            model_name='profilepicture',
            name='guy',
        ),
        migrations.DeleteModel(
            name='Girl',
        ),
        migrations.DeleteModel(
            name='Guy',
        ),
    ]
