# Generated by Django 5.1.4 on 2025-01-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('bi', 'Bi-sexual')], max_length=50)),
                ('category', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('api_model', models.CharField(max_length=255)),
                ('prompts', models.TextField()),
                ('views', models.IntegerField(default=0)),
            ],
        ),
    ]
