# Generated by Django 5.1.4 on 2025-01-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichat', '0002_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='amount',
            field=models.IntegerField(default=5000),
        ),
        migrations.AddField(
            model_name='profile',
            name='pay',
            field=models.BooleanField(default=False),
        ),
    ]
