# Generated by Django 5.1.4 on 2025-01-15 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aichat', '0003_profile_amount_profile_pay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='amount',
        ),
    ]
